name: "Release"

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v1"
      - name: "Setup Node.js"
        uses: "actions/setup-node@v1"
        with:
          node-version: "12.x"
      - name: "Install dependencies"
        run: |
          npm ci
      - name: "Build"
        run: |
          npm run build
        env:
          CI: true
          USERSCRIPTER_MODE: production
          USERSCRIPTER_VERBOSE: true
      - name: "Create GitHub release"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            animemusic-scraper.exe
            LICENSE
