name: Build and release scraper

on:
  push:
    tags:
      - "*"

jobs:
  gh_tagged_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Install and build
        run: |
            npm run install
            npm run build

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.ACTIONS_DEPLOY_KEY }}"
          prerelease: false
          files: |
            animemusic-scraper.exe
            LICENSE
